### ISSUE TITLE
util.Credentials missing

### ISSUE THREAD

**Issue by vadbut** [SKrotkih/YTLiveVideo-Android#3]
Thank you for this demo!
I might be misinterpreting the instructions, but I'm having a hard time figuring out where I should be looking for "**Credentials_.kt file (util folder)**". There is no file named Credentials_.kt in the repository or files generated during the build process.
Consequently, when I try to compile the app in Andoird Studio, it give me an error:
`.../YTLiveVideo-Android/app/src/main/java/com/skdev/ytlivevideo/ui/youtubePlayer/YouTubePlayerActivity.kt: (31, 35): Unresolved reference: Credentials`

What am I missing?

**Comment by SKrotkih** [comment]
Hi Vadim
I’ve cloned the repo. As you can see the file is presented. Please check it again.

**Comment by vadbut** [comment]
My bad, now I see it.
I was looking for Credentials_.kt, while the file is called Credentilals_.kt (with an extra "l").
